/**---------------------------------------------------
- TAP JavaDataFrame: Class that provides the implementation
         of a dynamic proxy that intercepts operations
        executed by the dataframes
    @author Gabriel Garcia
/----------------------------------------------------*/
import java.lang.reflect.InvocationHandler;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.lang.reflect.Proxy;
import java.util.List;

public class DynamicProxy implements InvocationHandler {
    private Object target;
    private List<Observer> observers; // List of observers that we can attach to the dynamic proxy to refine his interceptions

    /**
     * Generates an object through the dynamic proxy (reflection)
     * @param target object to instantiate
     * @param observers list of observers to attach when creating the proxy
     * @return the object generated by the proxy static call
     */
    public static Object newInstance(Object target, List<Observer> observers){
        Class<?> targetClass = target.getClass();
        Class[] interfaces = targetClass.getInterfaces();

        return Proxy. newProxyInstance(targetClass.getClassLoader(),
                interfaces, new DynamicProxy(target, observers));
    }

    /*We will only be able to attach observers when we instantiate*/
    /**
     * Private constructor that will be called when instantiating (newInstance)
     * @param target object to instantiate
     * @param observers list of observers attached to the proxy
     */
    private DynamicProxy(Object target,List<Observer> observers) {
        this.target = target;
        this.observers = observers;
    }

    /**
     *  Reflective proxy method to invoke a method
     * @param proxy object over which we will invoke the method
     * @param method method to invoke
     * @param args arguments of the method
     * @return result of the call
     */
    /*NOTE: We will not be able to attach any observer directly into the proxy because we are not going to instantiate
     * the proxy by itself*/
    public Object invoke(Object proxy, Method method, Object[] args) {
        Object invocationResult = null;
        try
        {
            System.out.println("Before method " + method.getName());
            invocationResult = method.invoke(this.target, args);
            System.out.println("After method " + method.getName());
        }
        catch(InvocationTargetException ite)
        {
            throw ite.getTargetException();
        }
        catch(Exception e)
        {
            System.err.println("Invocation of " + method.getName() + " failed");
        }
        finally{
            notifyAllObservers(method.getName(),args);
            return invocationResult;
        }
    }


    /*Observer Method */

    /**
     * Observer pattern method to notify all the observers which will be called when we invoke (to log) a method of an object
     * instantiated by the dynamic proxy
     * @param methodName name of the invoked method
     * @param args arguments of the method invoked (for the queryObserver)
     */
    public void notifyAllObservers(String methodName, Object[]args){
        for (Observer observer : observers) {
            observer.update(methodName, args);
        }
    }

}
